name: Build Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          path: theos
          submodules: recursive
      
      - name: Add Theos to PATH
        run: echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV

      - name: Build
        run: |
          git clone https://github.com/xybp888/iOS-SDKs $THEOS/sdks/
          mv $THEOS/sdks/iPhoneOS14.5.sdk $THEOS/sdks/iPhoneOS.sdk
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AIProMenu_DEB
          path: packages/*.deb
